title: Mauricio M. Caceres Bravo
description: My personal website
author: Mauricio M. Caceres Bravo
logo: /assets/mauricio-wm-ch.jpg
github: https://github.com/mcaceresb
about: Assistant Professor at Baruch College, CUNY
description: > # this means to ignore newlines until "baseurl:"
    Hi! I am an Assistant Professor at the Department of Economics and
    Finance in Baruch College's Zicklin School of Business, part of the City
    University of New York (CUNY). Welcome to my personal website, where
    you'll find information on my research projects, coding, and teaching.

    I received my PhD in Economics from Brown University in Providence, RI.
    I have Bachelor's degrees in mathematics and economics from the University
    of Utah and I have a Master's degree in economics from Columbia University
    in New York.
baseurl: ""
url: https://mcaceresb.github.io

allowsearch: true

github_username: mcaceresb
medium_username: mcaceresb
# google_tags: GTM-5JHMCV7
google_analytics: UA-91854317-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "blog/page:num/"
markdown: kramdown
highlighter: false
kramdown:
  syntax_highlighter_opts:
    disable : true
gems: [jekyll-paginate, jekyll-gist]
