title: Mauricio Cáceres Bravo
description: My personal website
author: Mauricio Cáceres Bravo
logo: /jekyll-hcz-blog/static/img/avatar.png
github: https://github.com/mcaceresb
about: Research Assistant at Yale SOM

baseurl: ""
url: ""

allowsearch: true

medium_username: mcaceresb
# google_tags: GTM-5JHMCV7
google_analytics: UA-91854317-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "blog/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
