title: Mauricio Cáceres Bravo
description: My personal website
author: Mauricio Cáceres Bravo
logo: /assets/mauricio-wm-ch.jpg
github: https://github.com/mcaceresb
about: Research Assistant at Yale SOM
description: > # this means to ignore newlines until "baseurl:"
    Hi! I am a research assistant at the Yale School of Management,
    based in New Haven, CT. This is my personal website, meant to
    force myself to speed along some coding projects I've had in the
    back-burner throughout the past year.

    I double-majored in mathematics and economics at the University
    of Utah and I have a Master's degree in economics from Columbia
    University in New York.
baseurl: ""
url: https://mcaceresb.github.io

allowsearch: true

github_username: mcaceresb
medium_username: mcaceresb
# google_tags: GTM-5JHMCV7
google_analytics: UA-91854317-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "blog/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
